# flake8: noqa: E501,Q000

SKILL_REVIEW_PROMPT = (
    "Review the conversation above and determine whether a reusable skill should be created or updated.\n\n"
    "If the conversation reveals a good workflow, troubleshooting procedure, or general methodology, "
    "summarize it as a skill. A reusable method for handling a class of problems is enough; "
    "it does not need to prove that any previous skill is outdated. Do not save just the answer "
    "to one specific problem.\n\n"
    "First, identify the applicable scenario for the skill. "
    "This scenario must be placed ONLY in the frontmatter `description` field, "
    "and it should state when the skill applies, not what happened in this conversation. "
    "Do NOT repeat the applicable scenario, trigger conditions, or any 'Applicable Scope' / 'When to use' section in the skill body.\n\n"
    "Then summarize the skill body as an abstract SOP. "
    "The SOP must generalize beyond the current case and explain how to approach similar tasks step by step, "
    "including tool selection order, branching logic, validation steps, and fallback strategy.\n\n"
    "Do NOT include in the body:\n"
    "- the applicable scenario / trigger conditions / when-to-use (these belong only in `description`)\n"
    "- the user's exact question\n"
    "- concrete examples from this conversation\n"
    "- specific entities, numbers, links, filenames, or outputs unless they are universally part of the procedure\n"
    "- a fact sheet, glossary, or result summary\n\n"
    "Do include in the body:\n"
    "- ordered workflow / tool sequence\n"
    "- reusable decision criteria and stopping conditions\n"
    "- concise scope boundaries that are not covered by `description`\n\n"
    "Keep the skill compact. "
    "The final skill must be no more than 1000 Chinese characters (or equivalent length in other languages). "
    "Prefer a short, high-density SOP over a detailed explanation.\n\n"
    "If a relevant existing skill already covers this scenario, update it rather than creating a duplicate. "
    "But only skills with `source=remote` are writable; if a matching skill has `source=file` or another "
    "non-remote source, treat it as read-only and do not call skill_editor to modify or remove it.\n\n"
    "# Incremental update rules (CRITICAL)\n"
    "- If existing skill content is provided by get_skill(), you MUST read it first.\n"
    "- Base your modification suggestions on the existing content; do NOT propose a blind rewrite from scratch.\n"
    "- Retain all still-valid existing workflow steps, criteria, and constraints.\n"
    "- Add newly discovered reusable workflow steps, decision criteria, validation steps, or fallback strategy.\n"
    "- When the new workflow conflicts with existing skill content, the new takes precedence "
    "unless the user explicitly stated the current behavior is temporary.\n"
    "- Keep the overall structure/format of the existing skill; do not reformat unnecessarily.\n"
    "- If no skill changes are needed, do not call skill_editor.\n"
    "- skill_editor records proposals for later review; it does NOT directly overwrite the final stored skill.\n\n"
    "Before modifying a skill, you MUST call get_skill() first to read its current content, "
    "then decide what to change based on the conversation. "
    "Only remove a skill when it is clearly invalid or should not exist; do not make removal the default path. "
    "Before removing a skill, you MUST call get_skill() first to confirm the content matches "
    "what you intend to delete.\n\n"
    "When calling skill_editor, identify the target skill by both `category` and `name`.\n\n"
    "If there is a worthwhile skill to create, modify, or remove, directly call skill_editor to submit the proposal. "
    "If the conversation does not contain a sufficiently generalizable workflow, reply with `Nothing to save` "
    "and a brief reason explaining why no skill proposal is warranted."
)

_MEMORY_REVIEW_LANGUAGE_RULES = (
    "# Language\n"
    "- Determine the language of new or rewritten memory/user profile content from `current_content` "
    "(or existing stored content shown in EXISTING STATE) and the conversation `history` / `llm_chat_history`.\n"
    "- If current content is non-empty, preserve that language unless the user explicitly asks for another language.\n"
    "- If current content is empty, use the dominant language of the user's messages in history; Chinese user messages should produce Chinese memory/user profile content.\n"
    "- Apply this to `replace_text.new` and `replace_all.content`; do not switch to English just because these instructions are written in English.\n\n"
)

MEMORY_REVIEW_PROMPT = (
    "Review the conversation above and consider saving durable memory if appropriate.\n\n"
    "Be conservative with memory changes (target='memory'): save only concise agent working memory that is likely to help in future sessions, "
    "such as when the discussion happened, what the user and agent discussed, what the user was working on, "
    "or other session-history facts the agent may need to recall later.\n"
    "For user profile changes (target='user'): save user-stated identity, role, preferred "
    "name/nickname, communication tone, language preference, output format, level of detail, and "
    "taboos. When the user explicitly states 'I like X', 'call me Y', or similar self-descriptions, "
    "these are intentional identity signals and should be saved.\n\n"
    "# Prefer skills over memory for workflows\n"
    "Do NOT save multi-step reusable workflows, troubleshooting procedures, lessons learned, "
    "tool usage patterns, implementation recipes, or task-specific conventions as memory. "
    "Those belong in skills. If skill_editor is available, create or update a skill instead. "
    "If skill_editor is not available, do not save them as memory; reply exactly: Nothing to save.\n\n"
    "# Quality filter — do NOT save trivial details\n"
    "Memory is for genuinely important, non-obvious information only. "
    "Before saving, ask: is this a concise session-memory fact the agent may need later? "
    "Do NOT save: obvious code patterns derivable from the repo, workflow notes better represented as skills, "
    "or anything the user wouldn't need recalled later. "
    "User-stated identity, preferred names/nicknames, and explicit communication "
    "preferences are NOT 'trivial details' or 'passing remarks' — save them as user profile content.\n"
    "For memory: err on the side of saving too little — sparse, high-signal memory "
    "is better than bloated memory full of noise. "
    "For user profile: when the user explicitly states a preference about "
    "themselves, default to saving it.\n\n"
    f"{_MEMORY_REVIEW_LANGUAGE_RULES}"
    "# Distinction between memory and user\n"
    "Call memory_editor(target='memory', operations=[...]) only for: concise agent working-memory notes about the user's ongoing work, "
    "what was discussed, and other future-relevant session context. The operations must edit the full current memory text.\n"
    "Call memory_editor(target='user', operations=[...]) for: user identity/role, preferred name/nickname, communication tone, "
    "language preference, output format, level of detail, or taboos that are stable across many tasks. "
    "Do NOT save workflow preferences, workflow steps, SOPs, tool sequences, or task procedures as user profile content.\n"
    "One fact must live in ONLY one place. If a fact could fit either target, "
    "choose the more specific one — do NOT duplicate across both. "
    "Review both current memory and user profile content (shown below) before writing; "
    "if the same fact already exists in the wrong target, move it and clean up the old location.\n\n"
    "# Incremental update rules (CRITICAL)\n"
    "- If existing content is provided below in 'EXISTING STATE', you MUST read it first.\n"
    "- Base your operations on the existing content; do NOT propose a blind rewrite from scratch.\n"
    "- Retain all still-valid existing entries as-is.\n"
    "- Add new content only for newly discovered memory events or explicit updates to older memory.\n"
    "- When new information conflicts with existing entries, the new takes precedence "
    "unless the user explicitly stated the current state is temporary.\n"
    "- Remove or update only what is proven outdated or wrong; express the change with replace_text or replace_all operations.\n"
    "- Keep the overall structure/format of the existing content; do not reformat unnecessarily.\n"
    "- If no changes are needed, do not call memory_editor at all.\n"
    "- memory_editor requires exactly target and operations.\n"
    "- Prefer replace_text with exact old text copied from current content. Use replace_all only when current content is empty or a full rewrite is truly necessary.\n"
    "When in doubt about memory, do NOT save — only write when you are confident. "
    "For user profile content: if the user explicitly stated a preference or identity, save it. "
    "Only skip user profile content when the information is clearly ephemeral "
    "(e.g., 'I'm tired today').\n"
    "The outdated/wrong removal-or-correction gate above is specific to memory and user profile content; "
    "do not use memory review as a substitute for skill creation.\n"
    "If there is a worthwhile memory or user profile change, directly call memory_editor with operations. "
    "If nothing is worth saving or updating, reply with `Nothing to save` and a brief reason explaining why no "
    "memory or user update is warranted."
)

COMBINED_REVIEW_PROMPT = (
    "Review the conversation above and decide whether exactly one durable update should be saved.\n\n"
    "You have exactly three tool choices, and you must call at most one of them: memory_editor, skill_editor, or vocab_learn. "
    "Choose the single best tool for this conversation. Do not call multiple tools in the same review.\n\n"
    "# Memory updates\n"
    "Be conservative with memory updates (target='memory'): save only concise agent working memory "
    "that may help in future sessions, such as when the discussion happened, "
    "what the user and agent discussed, what the user was working on, or "
    "other future-relevant session context.\n"
    "For user profile updates (target='user'): save user-stated identity, role, "
    "preferred name/nickname, communication tone, language preference, output format, "
    "level of detail, and taboos. When the user explicitly states 'I like X', "
    "'call me Y', or similar self-descriptions, these are NOT 'passing remarks' — "
    "they are intentional identity signals and should be saved.\n\n"
    "Do NOT save multi-step reusable workflows, troubleshooting procedures, lessons learned, "
    "tool usage patterns, implementation recipes, or task-specific conventions as memory. "
    "Those belong in skills. When a conversation reveals a repeatable method, prefer "
    "skill_editor over memory.\n\n"
    "## Quality filter — do NOT save trivial details\n"
    "Memory is for genuinely important, non-obvious information only. "
    "Before saving, ask: is this a concise session-memory fact the agent may need later? "
    "Do NOT save: obvious code patterns derivable from the repo, workflow notes better represented as skills, "
    "or anything the user wouldn't need recalled later. "
    "User-stated identity, preferred names/nicknames, and explicit communication "
    "preferences are NOT 'trivial details' or 'passing remarks' — save them as user profile content.\n"
    "For memory: err on the side of saving too little — sparse, high-signal memory "
    "is better than bloated memory full of noise. "
    "For user profile: when the user explicitly states a preference about "
    "themselves, default to saving it.\n\n"
    f"{_MEMORY_REVIEW_LANGUAGE_RULES}"
    "## Distinction between memory and user\n"
    "Call memory_editor(target='memory', operations=[...]) only for: concise agent working-memory notes about the user's ongoing work, "
    "what was discussed, and other future-relevant session context. The operations must edit the full current memory text.\n"
    "Call memory_editor(target='user', operations=[...]) for: user identity/role, preferred name/nickname, communication tone, "
    "language preference, output format, level of detail, or taboos that are stable across many tasks. "
    "Do NOT save workflow preferences, workflow steps, SOPs, tool sequences, or task procedures as user profile content.\n"
    "One fact must live in ONLY one place. If a fact could fit either target, "
    "choose the more specific one — do NOT duplicate across both. "
    "Review both current memory and user profile content (shown below) before writing; "
    "if the same fact already exists in the wrong target, move it and clean up the old location.\n\n"
    "## Incremental update rules (CRITICAL)\n"
    "- If existing content is provided below in 'EXISTING STATE', you MUST read it first.\n"
    "- Base your operations on the existing content; do NOT propose a blind rewrite from scratch.\n"
    "- Retain all still-valid existing entries as-is.\n"
    "- Add new content only for newly discovered memory events or explicit updates to older memory.\n"
    "- When new information conflicts with existing entries, the new takes precedence "
    "unless the user explicitly stated the current state is temporary.\n"
    "- Remove or update only what is proven outdated or wrong; express the change with replace_text or replace_all operations.\n"
    "- Keep the overall structure/format of the existing content; do not reformat unnecessarily.\n"
    "- If no changes are needed, do not call memory_editor at all.\n"
    "- memory_editor requires exactly target and operations.\n"
    "- Prefer replace_text with exact old text copied from current content. Use replace_all only when current content is empty or a full rewrite is truly necessary.\n"
    "The outdated/wrong removal-or-correction gate above is specific to memory and user profile content; "
    "do not apply it as a prerequisite for creating useful skills.\n\n"
    "# Skill updates\n"
    "Save reusable multi-step workflows, troubleshooting procedures, tool usage patterns, or general methodologies as skills with skill_editor. "
    "If the conversation contains a good reusable workflow, summarize it as a skill and put the usage scenario in the `description` field. "
    "A general method for handling a class of problems is a reusable skill; it does not need to prove that any previous memory, preference, or skill is outdated. "
    "Prefer updating an existing skill if one already covers the task, but only when its `source=remote`; "
    "skills with `source=file` or any other non-remote source are read-only and must not be modified or removed. "
    "When updating an existing skill, follow the same incremental update discipline: read existing content first, "
    "preserve still-valid steps, add newly discovered reusable steps or criteria, prefer targeted edits over wholesale rewrites, "
    "and keep the existing structure unless changing it is necessary. "
    "If no skill changes are needed, do not call skill_editor. "
    "skill_editor records proposals for later review; it does NOT directly overwrite the final stored skill. "
    "Before modifying a skill, you MUST call get_skill() first to read its current content, "
    "then decide what to change based on the conversation. "
    "Only remove a skill when it is clearly invalid or should not exist; do not make removal the default path. "
    "Before removing a skill, you MUST call get_skill() first to confirm the content matches "
    "what you intend to delete. "
    "When calling skill_editor, identify the target skill by both `category` and `name`.\n\n"
    "# Vocabulary updates\n"
    "Use vocab_learn only for clear, user-specific vocabulary or terminology mappings explicitly established in the conversation. "
    "Use it when the user says one term means, equals, aliases, or should be remembered as another term in their domain. "
    "Do not use vocab_learn for vague paraphrases, temporary nicknames, or general world-knowledge synonyms.\n\n"
    "When in doubt about memory or skills, do NOT save — only write when you are confident. "
    "For user_preference: if the user explicitly stated a preference or identity, save it. "
    "Only skip user_preference when the information is clearly ephemeral "
    "(e.g., 'I'm tired today').\n"
    "Do not save ephemeral task state.\n"
    "If there is a worthwhile memory, user_preference, skill, or vocabulary change, directly call the appropriate single tool to submit the proposal. "
    "If nothing is worth saving, reply with `Nothing to save` and a brief reason explaining why no skill, memory, "
    "user_preference, or vocabulary proposal is warranted."
)

__all__ = [
    'COMBINED_REVIEW_PROMPT',
    'MEMORY_REVIEW_PROMPT',
    'SKILL_REVIEW_PROMPT',
]
