# flake8: noqa: E501,Q000

_MEMORY_REVIEW_LANGUAGE_RULES = (
    "# Language\n"
    "- Determine the language of new or rewritten memory/user profile content from `current_content` "
    "(or existing stored content shown in EXISTING STATE) and the conversation `history` / `llm_chat_history`.\n"
    "- If current content is non-empty, preserve that language unless the user explicitly asks for another language.\n"
    "- If current content is empty, use the dominant language of the user's messages in history; Chinese user messages should produce Chinese memory/user profile content.\n"
    "- Apply this to `replace_text.new` and `replace_all.content`; do not switch to English just because these instructions are written in English.\n\n"
)

MEMORY_REVIEW_PROMPT = (
    "Review the conversation above and consider saving durable memory if appropriate.\n\n"
    "Be conservative with memory changes (target='memory'): save only concise agent working memory that is likely to help in future sessions, "
    "such as when the discussion happened, what the user and agent discussed, what the user was working on, "
    "or other session-history facts the agent may need to recall later.\n"
    "For user profile changes (target='user'): save user-stated identity, role, preferred "
    "name/nickname, communication tone, language preference, output format, level of detail, and "
    "taboos. When the user explicitly states 'I like X', 'call me Y', or similar self-descriptions, "
    "these are intentional identity signals and should be saved.\n\n"
    "# Prefer skills over memory for workflows\n"
    "Do NOT save multi-step reusable workflows, troubleshooting procedures, lessons learned, "
    "tool usage patterns, implementation recipes, or task-specific conventions as memory. "
    "Those belong in skills. If skill_editor is available, create or update a skill instead. "
    "If skill_editor is not available, do not save them as memory; reply exactly: Nothing to save.\n\n"
    "# Quality filter -- do NOT save trivial details\n"
    "Memory is for genuinely important, non-obvious information only. "
    "Before saving, ask: is this a concise session-memory fact the agent may need later? "
    "Do NOT save: obvious code patterns derivable from the repo, workflow notes better represented as skills, "
    "or anything the user wouldn't need recalled later. "
    "User-stated identity, preferred names/nicknames, and explicit communication "
    "preferences are NOT 'trivial details' or 'passing remarks' -- save them as user profile content.\n"
    "For memory: err on the side of saving too little -- sparse, high-signal memory "
    "is better than bloated memory full of noise. "
    "For user profile: when the user explicitly stated a preference about "
    "themselves, default to saving it.\n\n"
    f"{_MEMORY_REVIEW_LANGUAGE_RULES}"
    "# Distinction between memory and user\n"
    "Call memory_editor(target='memory', operations=[...]) only for: concise agent working-memory notes about the user's ongoing work, "
    "what was discussed, and other future-relevant session context. The operations must edit the full current memory text.\n"
    "Call memory_editor(target='user', operations=[...]) for: user identity/role, preferred name/nickname, communication tone, "
    "language preference, output format, level of detail, or taboos that are stable across many tasks. "
    "Do NOT save workflow preferences, workflow steps, SOPs, tool sequences, or task procedures as user profile content.\n"
    "One fact must live in ONLY one place. If a fact could fit either target, "
    "choose the more specific one -- do NOT duplicate across both. "
    "Review both current memory and user profile content before writing; "
    "if the same fact already exists in the wrong target, move it and clean up the old location.\n\n"
    "# Incremental update rules (CRITICAL)\n"
    "- If existing content is provided below in current content / EXISTING STATE, you MUST read it first.\n"
    "- Base your operations on the existing content; do NOT propose a blind rewrite from scratch.\n"
    "- Retain all still-valid existing entries as-is.\n"
    "- Add new content only for newly discovered memory events or explicit updates to older memory.\n"
    "- When new information conflicts with existing entries, the new takes precedence "
    "unless the user explicitly stated the current state is temporary.\n"
    "- Remove or update only what is proven outdated or wrong; express the change with replace_text or replace_all operations.\n"
    "- Keep the overall structure/format of the existing content; do not reformat unnecessarily.\n"
    "- If no changes are needed, do not call memory_editor at all.\n"
    "- memory_editor requires exactly target and operations.\n"
    "- Prefer replace_text with exact old text copied from current content. Use replace_all only when current content is empty or a full rewrite is truly necessary.\n"
    "When in doubt about memory, do NOT save -- only write when you are confident. "
    "For user profile content: if the user explicitly stated a preference or identity, save it. "
    "Only skip user profile content when the information is clearly ephemeral "
    "(e.g., 'I'm tired today').\n"
    "The outdated/wrong removal-or-correction gate above is specific to memory and user profile content; "
    "do not use memory review as a substitute for skill creation.\n"
    "If there is a worthwhile memory or user profile change, directly call memory_editor with operations. "
    "If nothing is worth saving or updating, reply with `Nothing to save` and a brief reason explaining why no "
    "memory or user update is warranted."
)

__all__ = [
    'MEMORY_REVIEW_PROMPT',
]
